name: gesvol
description: Gestione Volontari
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cloud_firestore: ^4.4.3
  cupertino_icons: ^1.0.5
  extension_google_sign_in_as_googleapis_auth: ^2.0.9
  firebase_analytics: ^10.1.4
  firebase_auth: ^4.2.9
  firebase_core: ^2.7.0
  firebase_crashlytics: ^3.0.15
  flutter_secure_storage: ^8.0.0
  flutter_signin_button: ^2.0.0
  get: ^4.6.5
  googleapis_auth: ^1.3.1
  google_fonts: ^4.0.3
  google_sign_in: ^6.0.0
  googleapis: ^10.1.0
  http: ^0.13.5
  intl: ^0.17.0
  open_file: ^3.2.1
  syncfusion_flutter_barcodes: ^20.4.51
  syncfusion_flutter_calendar: ^20.4.51
  syncfusion_flutter_charts: ^20.4.51
  syncfusion_flutter_core: ^20.4.51
  syncfusion_flutter_datagrid: ^20.4.51
  syncfusion_flutter_datagrid_export: ^20.4.51-beta
  syncfusion_flutter_datepicker: ^20.4.51
  syncfusion_flutter_gauges: ^20.4.51
  syncfusion_flutter_maps: ^20.4.51
  syncfusion_flutter_pdf: ^20.4.49
  syncfusion_flutter_pdfviewer: ^20.4.51
  syncfusion_flutter_signaturepad: ^20.4.51
  syncfusion_flutter_sliders: ^20.4.51
  syncfusion_flutter_treemap: ^20.4.51-beta
  syncfusion_flutter_xlsio: ^20.4.51-beta
  syncfusion_localizations: ^20.4.51
  syncfusion_officechart: ^20.4.51-beta
  syncfusion_officecore: ^20.4.51-beta
  transparent_image: ^2.0.1
  url_launcher: ^6.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/logos/logo-cpgev.png
    - assets/images/bosco_autunnale.jpg
    - assets/images/nav-menu-header-bg.jpg
    - assets/icons/excel_icon.png
    - assets/icons/adobe_icon.png
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
