// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_xzGZco-DSdhYDQmjsSWIaPLYAraWuJU',
    appId: '1:158895990793:web:96cc2f8bf1a5c8f19830d8',
    messagingSenderId: '158895990793',
    projectId: 'gesvol-6a1b7',
    authDomain: 'gesvol-6a1b7.firebaseapp.com',
    storageBucket: 'gesvol-6a1b7.appspot.com',
    measurementId: 'G-29YJZQNS2L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMeJv7jf64eQGUpZNJnrijAvxrqDRAd6Y',
    appId: '1:158895990793:android:35f6cba9a0e3e9a69830d8',
    messagingSenderId: '158895990793',
    projectId: 'gesvol-6a1b7',
    storageBucket: 'gesvol-6a1b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNQOSar1aKYF3tdsffePoq2n9RgSvQwgw',
    appId: '1:158895990793:ios:0472a6086052b2289830d8',
    messagingSenderId: '158895990793',
    projectId: 'gesvol-6a1b7',
    storageBucket: 'gesvol-6a1b7.appspot.com',
    iosClientId: '158895990793-hgjkh9pikqq8no76bvl8gdgmsk68qomi.apps.googleusercontent.com',
    iosBundleId: 'com.example.gesvol',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNQOSar1aKYF3tdsffePoq2n9RgSvQwgw',
    appId: '1:158895990793:ios:0472a6086052b2289830d8',
    messagingSenderId: '158895990793',
    projectId: 'gesvol-6a1b7',
    storageBucket: 'gesvol-6a1b7.appspot.com',
    iosClientId: '158895990793-hgjkh9pikqq8no76bvl8gdgmsk68qomi.apps.googleusercontent.com',
    iosBundleId: 'com.example.gesvol',
  );
}
